import type { UniversityQuizQuestion } from "./quiz";

export const EXAM_SET_B: UniversityQuizQuestion[] = [
  {
    id: "b1",
    lessonId: "intro-crypto",
    prompt: "Why is Bitcoin often treated as the reference asset for the crypto market?",
    options: [
      "It is the oldest major crypto network and largest liquidity benchmark",
      "It is issued by the Federal Reserve",
      "It is a stablecoin designed to stay at $1",
      "It can only be traded on decentralized exchanges",
    ],
    correctIndex: 0,
  },
  {
    id: "b2",
    lessonId: "chart-basics",
    prompt: "What do OHLC stand for on a candlestick?",
    options: [
      "Open, High, Low, Close",
      "Order, Hedge, Lot, Contract",
      "Only High Liquidity Candles",
      "Overnight Holding Limit Cost",
    ],
    correctIndex: 0,
  },
  {
    id: "b3",
    lessonId: "chart-basics",
    prompt: "Wicks (shadows) on a candle show:",
    options: [
      "The period’s extreme high and low beyond the body",
      "Only the exchange’s funding rate",
      "Your broker’s swap fee",
      "The exact liquidation price of every trader",
    ],
    correctIndex: 0,
  },
  {
    id: "b4",
    lessonId: "orders-execution",
    prompt: "A stop order (stop-market) typically:",
    options: [
      "Becomes a market order when a trigger price is hit",
      "Fills only at your limit price forever",
      "Deletes funding rates",
      "Locks Fib levels on the chart",
    ],
    correctIndex: 0,
  },
  {
    id: "b5",
    lessonId: "wallets-security",
    prompt: "What is the safest assumption when a website asks for your recovery phrase?",
    options: [
      "It is likely malicious, because legitimate apps do not need the phrase",
      "It is required for every normal token swap",
      "It only proves wallet ownership and cannot move funds",
      "It is safe if the website has a polished logo",
    ],
    correctIndex: 0,
  },
  {
    id: "b6",
    lessonId: "wallets-security",
    prompt: "Why should token approvals be reviewed after trading risky meme coins?",
    options: [
      "Some approvals can let contracts move tokens later if left unlimited",
      "Approvals automatically create a stop-loss order",
      "Approvals prevent all honeypots from working",
      "Approvals convert hot wallets into cold wallets",
    ],
    correctIndex: 0,
  },
  {
    id: "b7",
    lessonId: "psychology-journaling",
    prompt: "After a full stop-out, a healthy default is:",
    options: [
      "Take a cooldown (one candle or a fixed pause) before the next idea",
      "Immediately double size to recover",
      "Delete the journal entry so it never happened",
      "Move the next stop farther away by default",
    ],
    correctIndex: 0,
  },
  {
    id: "b8",
    lessonId: "psychology-journaling",
    prompt: "Tagging journal entries as 'followed plan' vs 'broke plan' mainly helps you:",
    options: [
      "See whether edge comes from process — not only from P&L screenshots",
      "Hide losses from yourself",
      "Prove every trade was perfect",
      "Skip writing invalidation forever",
    ],
    correctIndex: 0,
  },
  {
    id: "b9",
    lessonId: "risk-fundamentals",
    prompt: "A trader risking 1% per setup is primarily controlling:",
    options: [
      "The maximum planned account damage if the idea is wrong",
      "The exact profit target the market must reach",
      "The exchange's liquidation engine",
      "The number of followers a token account receives",
    ],
    correctIndex: 0,
  },
  {
    id: "b10",
    lessonId: "risk-fundamentals",
    prompt: "Why does a stop level belong in the plan before entering a position?",
    options: [
      "It defines where the trade thesis is no longer valid",
      "It guarantees a fill with no slippage",
      "It forces the trade to close in profit",
      "It removes fees from the execution",
    ],
    correctIndex: 0,
  },
  {
    id: "b11",
    lessonId: "risk-fundamentals",
    prompt: "Which habit usually reduces blow-up risk during a losing streak?",
    options: [
      "Reducing size or pausing instead of doubling down emotionally",
      "Increasing leverage after every loss",
      "Ignoring the original invalidation level",
      "Moving all funds into one launch token",
    ],
    correctIndex: 0,
  },
  {
    id: "b12",
    lessonId: "forex",
    prompt: "On EUR/USD (~$1/pip per 0.10 lot), risking about $20 on a 20-pip stop implies roughly:",
    options: [
      "0.10 lot size (before spread)",
      "1.0 standard lot only",
      "0.01 lot for a $200 risk",
      "No lot size — pips are not dollars",
    ],
    correctIndex: 0,
  },
  {
    id: "b13",
    lessonId: "meme-coins",
    prompt: "Why can meme coins move violently without news about revenue or products?",
    options: [
      "Attention, narrative, and liquidity can dominate fundamentals",
      "They are all backed by insured bank deposits",
      "They settle only once per month",
      "Their prices are fixed by validators",
    ],
    correctIndex: 0,
  },
  {
    id: "b14",
    lessonId: "meme-coins",
    prompt: "Which holder pattern is a red flag for a new meme token?",
    options: [
      "A few wallets control a large share of supply",
      "Many small wallets hold tiny balances",
      "The token has a public chart",
      "The token trades against a stablecoin pair",
    ],
    correctIndex: 0,
  },
  {
    id: "b15",
    lessonId: "meme-coins",
    prompt: "A liquidity lock or burned LP is checked because it can show whether:",
    options: [
      "The team can easily pull pool liquidity",
      "The token will always trend on social media",
      "The chart must keep rising",
      "The contract has no buy tax",
    ],
    correctIndex: 0,
  },
  {
    id: "b16",
    lessonId: "novastaris-workflow",
    prompt: "If two NovaStaris tools disagree on a setup, a good default is:",
    options: [
      "Reduce size or stand aside — disagreement is information",
      "Double size to average out uncertainty",
      "Ignore both and chase social FOMO",
      "Disable all feature flags",
    ],
    correctIndex: 0,
  },
  {
    id: "b17",
    lessonId: "market-structure",
    prompt: "Break of structure (BOS) in an uptrend often means:",
    options: [
      "Price takes out a prior swing high and the trend context may still be intact",
      "You must immediately go all-in short",
      "Funding rates reset to zero",
      "The pair can no longer form a range",
    ],
    correctIndex: 0,
  },
  {
    id: "b18",
    lessonId: "market-structure",
    prompt: "CHOCH (change of character) is best treated as:",
    options: [
      "An early hint a trend may be shifting — wait for follow-through or tight invalidation",
      "An automatic all-in reverse signal",
      "A Solana mint authority flag",
      "A prop-firm banned strategy list",
    ],
    correctIndex: 0,
  },
  {
    id: "b19",
    lessonId: "ethereum-l2s",
    prompt: "Before swapping a token on an EVM chain you should first:",
    options: [
      "Confirm the wallet network matches the contract’s chain",
      "Disable gas fees permanently",
      "Paste the CA while ignoring the network selector",
      "Share your seed with the bridge support chat",
    ],
    correctIndex: 0,
  },
  {
    id: "b20",
    lessonId: "options-volatility",
    prompt: "A long call option buyer’s typical max loss (fees aside) is:",
    options: [
      "The premium paid",
      "Unlimited like a naked 125× perp liquidation",
      "Only the overnight forex swap",
      "Zero — calls cannot expire worthless",
    ],
    correctIndex: 0,
  },
  {
    id: "b21",
    lessonId: "solana",
    prompt: "What does SOL pay for when you submit a normal transaction?",
    options: [
      "Network fees and, when chosen, priority fees",
      "A guaranteed listing on every CEX",
      "The token's future marketing budget",
      "The forex broker spread",
    ],
    correctIndex: 0,
  },
  {
    id: "b22",
    lessonId: "solana",
    prompt: "Why do traders often verify a Solana mint address before swapping?",
    options: [
      "Similar token names can point to completely different assets",
      "The mint address reveals the trader's seed phrase",
      "A verified mint removes all price volatility",
      "Only fake tokens have mint addresses",
    ],
    correctIndex: 0,
  },
  {
    id: "b23",
    lessonId: "solana",
    prompt: "What is a common reason Solana users increase priority fees during congestion?",
    options: [
      "To compete for faster transaction inclusion",
      "To permanently lower token taxes",
      "To turn a DEX swap into a CEX order",
      "To reduce the circulating supply of Bitcoin",
    ],
    correctIndex: 0,
  },
  {
    id: "b24",
    lessonId: "solana-memes",
    prompt: "In many Solana meme launches, what happens when a bonding curve completes?",
    options: [
      "Liquidity may migrate to a DEX pool for open trading",
      "The token becomes a fiat bank account",
      "All early buyers are liquidated",
      "The project automatically receives a patent",
    ],
    correctIndex: 0,
  },
  {
    id: "b25",
    lessonId: "solana-memes",
    prompt: "Why is early Solana meme trading considered especially risky?",
    options: [
      "Projects may have little history, thin liquidity, and concentrated ownership",
      "SOL transactions cannot fail",
      "Every new token is backed by USDC",
      "Validators choose winners manually",
    ],
    correctIndex: 0,
  },
  {
    id: "b26",
    lessonId: "solana-memes",
    prompt: "What does a quick check of top holders help a Solana meme trader estimate?",
    options: [
      "Whether a few wallets could dump heavily into buyers",
      "The exact next funding payment",
      "The pip value of USD/JPY",
      "The official market resolution date",
    ],
    correctIndex: 0,
  },
  {
    id: "b27",
    lessonId: "bsc-memes",
    prompt: "A BSC honeypot is dangerous because a trader may be able to:",
    options: [
      "Buy the token but fail to sell it normally",
      "Sell the token without first buying it",
      "Avoid all tax and gas costs",
      "Convert BNB into Bitcoin mining rewards",
    ],
    correctIndex: 0,
  },
  {
    id: "b28",
    lessonId: "bsc-memes",
    prompt: "Why do BSC meme traders check buy and sell tax before entering?",
    options: [
      "High or changeable taxes can make exits much worse than expected",
      "Taxes determine the global Bitcoin hash rate",
      "A tax means the token is always audited",
      "A tax replaces the need for liquidity",
    ],
    correctIndex: 0,
  },
  {
    id: "b29",
    lessonId: "bsc-memes",
    prompt: "What role does BNB usually play in BSC meme trading?",
    options: [
      "It pays gas and is often paired with tokens for liquidity",
      "It is the native coin of Solana",
      "It is a forex base currency",
      "It settles prediction markets at expiration",
    ],
    correctIndex: 0,
  },
  {
    id: "b30",
    lessonId: "crypto-futures",
    prompt: "What happens to both gains and losses when a trader uses 10x leverage?",
    options: [
      "They are magnified relative to the margin posted",
      "Losses disappear but gains remain",
      "The position becomes spot ownership",
      "Funding payments can no longer occur",
    ],
    correctIndex: 0,
  },
  {
    id: "b31",
    lessonId: "crypto-futures",
    prompt: "Why might liquidation trigger even if the last trade print looks 'safe'?",
    options: [
      "Many venues liquidate off mark/index price, which can differ from the last print",
      "Liquidation only uses Twitter sentiment",
      "Mark price is ignored on every venue",
      "Stops never use mark price",
    ],
    correctIndex: 0,
  },
  {
    id: "b32",
    lessonId: "crypto-futures",
    prompt: "What is the key difference between going long and going short on a perp?",
    options: [
      "A long benefits from price rising, while a short benefits from price falling",
      "A long pays no fees, while a short pays all fees",
      "A short can never be liquidated",
      "A long always owns the underlying token",
    ],
    correctIndex: 0,
  },
  {
    id: "b33",
    lessonId: "crypto-futures",
    prompt: "The main risk of cross margin for beginners is:",
    options: [
      "One bad position can contagion shared equity and threaten the rest of the book",
      "Cross margin deletes funding forever",
      "Cross margin makes liquidation impossible",
      "Cross margin converts perps into spot",
    ],
    correctIndex: 0,
  },
  {
    id: "b34",
    lessonId: "predictions",
    prompt: "If a prediction market Yes share trades at 72 cents, what does that roughly imply?",
    options: [
      "The market is pricing about a 72% chance before fees and other frictions",
      "The event pays 72 Bitcoin if correct",
      "The trader is using 72x leverage",
      "The market will resolve in 72 minutes",
    ],
    correctIndex: 0,
  },
  {
    id: "b35",
    lessonId: "predictions",
    prompt: "Why should prediction traders read resolution criteria before betting?",
    options: [
      "The exact wording determines what outcome will settle the market",
      "It reveals the private key of the market creator",
      "It removes all liquidity risk",
      "It sets the spread on EUR/USD",
    ],
    correctIndex: 0,
  },
  {
    id: "b36",
    lessonId: "meme-trading",
    prompt: "All-in trading cost on a meme buy should include:",
    options: [
      "Network fee + any tip/bribe + slippage/price impact (+ CEX fees if applicable)",
      "Only the token’s market-cap number",
      "Only the chart emoji on Telegram",
      "Funding rate alone",
    ],
    correctIndex: 0,
  },
  {
    id: "b37",
    lessonId: "forex",
    prompt: "For most major pairs quoted to four decimals, one pip is:",
    options: ["0.0001", "0.01", "1.0000", "100 pips"],
    correctIndex: 0,
  },
  {
    id: "b38",
    lessonId: "trading-styles",
    prompt: "Day trading typically means:",
    options: [
      "Intraday holds with the intent to be flat by session end",
      "Holding for weeks with weekly charts only",
      "Never using a stop-loss",
      "Only trading meme bonding curves",
    ],
    correctIndex: 0,
  },
  {
    id: "b39",
    lessonId: "market-structure",
    prompt: "In a ranging / chop regime, a common disciplined approach is:",
    options: [
      "Fade extremes near clear highs/lows — avoid mid-range overtrading",
      "Max size every mid-range candle",
      "Ignore highs and lows entirely",
      "Use only weekly charts for scalps",
    ],
    correctIndex: 0,
  },
  {
    id: "b40",
    lessonId: "orders-execution",
    prompt: "Why cancel open working orders when your thesis changes?",
    options: [
      "Stale limits/stops can fill and put you in an unwanted trade",
      "Exchanges ban accounts with open orders",
      "Working orders delete your journal",
      "Fib tools stop working if orders exist",
    ],
    correctIndex: 0,
  },
];

export const EXAM_SET_C: UniversityQuizQuestion[] = [
  {
    id: "c1",
    lessonId: "intro-crypto",
    prompt: "What makes a blockchain ledger different from a private spreadsheet?",
    options: [
      "Many network participants can verify updates under shared rules",
      "Only one bank employee can edit every balance",
      "It never needs cryptographic signatures",
      "It guarantees every listed token is safe",
    ],
    correctIndex: 0,
  },
  {
    id: "c2",
    lessonId: "chart-basics",
    prompt: "A chart timeframe (e.g. 5m or 1h) means:",
    options: [
      "How long each candle represents",
      "The broker’s overnight swap rate",
      "The number of pips in a lot",
      "Your account’s KYC tier",
    ],
    correctIndex: 0,
  },
  {
    id: "c3",
    lessonId: "chart-basics",
    prompt: "An engulfing candle is most useful when:",
    options: [
      "Its body fully covers the prior body and appears at an extreme — not mid-chop alone",
      "It appears anywhere and guarantees a 10× move",
      "It removes the need for a stop-loss",
      "It only appears on forex majors",
    ],
    correctIndex: 0,
  },
  {
    id: "c4",
    lessonId: "chart-basics",
    prompt: "A hammer candle is typically described as:",
    options: [
      "Small body near the high with a long lower wick — possible rejection of lows",
      "A funding payment from longs to shorts",
      "A guaranteed short signal",
      "An open limit order on the exchange",
    ],
    correctIndex: 0,
  },
  {
    id: "c5",
    lessonId: "wallets-security",
    prompt: "Which item is safe to share when receiving funds?",
    options: [
      "Your public wallet address",
      "Your seed phrase",
      "Your hardware wallet PIN",
      "Your private key",
    ],
    correctIndex: 0,
  },
  {
    id: "c6",
    lessonId: "wallets-security",
    prompt: "What is the risk of signing a transaction you do not understand?",
    options: [
      "You may authorize token transfers, approvals, or malicious actions",
      "It only changes your chart theme",
      "It creates a guaranteed arbitrage",
      "It prevents the transaction from reaching the network",
    ],
    correctIndex: 0,
  },
  {
    id: "c7",
    lessonId: "wallets-security",
    prompt: "Which habit best reduces wallet phishing and drain risk?",
    options: [
      "Never share the seed phrase, review approvals, and verify URLs before connecting",
      "Paste your recovery phrase into any site that asks to 'verify ownership'",
      "Approve unlimited spends on every new token forever",
      "Store your private key in a public Discord channel",
    ],
    correctIndex: 0,
  },
  {
    id: "c8",
    lessonId: "wallets-security",
    prompt: "What should you do before connecting a wallet to an unfamiliar trading site?",
    options: [
      "Check the URL, permissions, and whether the site is trusted",
      "Paste your recovery phrase to confirm identity",
      "Move all savings into the same hot wallet",
      "Increase slippage to the maximum",
    ],
    correctIndex: 0,
  },
  {
    id: "c9",
    lessonId: "risk-fundamentals",
    prompt: "What does position sizing answer before a trade is opened?",
    options: [
      "How much capital should be used for the defined risk",
      "Which influencer will mention the token next",
      "Which validator produces the next block",
      "Whether the exchange will list the coin tomorrow",
    ],
    correctIndex: 0,
  },
  {
    id: "c10",
    lessonId: "psychology-journaling",
    prompt: "Why is a trade journal useful?",
    options: [
      "It helps identify repeated mistakes and whether a strategy is working",
      "It guarantees every entry has positive expectancy",
      "It removes the need for stop-loss planning",
      "It makes liquidity checks unnecessary",
    ],
    correctIndex: 0,
  },
  {
    id: "c11",
    lessonId: "risk-fundamentals",
    prompt: "Which action is most consistent with disciplined risk management?",
    options: [
      "Skipping a setup when the invalidation point is unclear",
      "Adding size because a chat room is excited",
      "Removing the stop after price moves against you",
      "Using maximum leverage because fees are low",
    ],
    correctIndex: 0,
  },
  {
    id: "c12",
    lessonId: "risk-fundamentals",
    prompt: "What is drawdown?",
    options: [
      "A decline from an account or strategy peak",
      "A DEX router address",
      "A stablecoin redemption fee",
      "A Jito transaction tip",
    ],
    correctIndex: 0,
  },
  {
    id: "c13",
    lessonId: "meme-coins",
    prompt: "Why can a meme token with thin liquidity be hard to exit?",
    options: [
      "Selling size can move the price heavily against the trader",
      "Thin liquidity guarantees no slippage",
      "Only CEX accounts can sell tokens",
      "Stablecoins block the sell order",
    ],
    correctIndex: 0,
  },
  {
    id: "c14",
    lessonId: "meme-coins",
    prompt: "What is a common warning sign in meme coin marketing?",
    options: [
      "Guaranteed-profit claims and urgent pressure to buy immediately",
      "Clear contract links and risk disclosures",
      "A public chart with visible liquidity",
      "Open discussion of token supply",
    ],
    correctIndex: 0,
  },
  {
    id: "c15",
    lessonId: "volume-vwap",
    prompt: "Point of control (POC) in a volume profile is:",
    options: [
      "The price with the most traded volume in that profile window",
      "Always your stop-loss level",
      "The Solana priority fee",
      "The prop-firm max leverage",
    ],
    correctIndex: 0,
  },
  {
    id: "c16",
    lessonId: "backtesting-expectancy",
    prompt: "Expectancy is best thought of as:",
    options: [
      "Average outcome per trade after wins and losses (often in R, after costs)",
      "Your highest single winning meme trade",
      "The chart’s RSI number alone",
      "A guarantee of future profits",
    ],
    correctIndex: 0,
  },
  {
    id: "c17",
    lessonId: "psychology-journaling",
    prompt: "FOMO entries after a clear move has already printed should usually mean:",
    options: [
      "Smaller size or no trade — not larger size to 'catch up'",
      "Maximum leverage to recover faster",
      "Deleting the daily loss limit",
      "Ignoring invalidation entirely",
    ],
    correctIndex: 0,
  },
  {
    id: "c18",
    lessonId: "trading-styles",
    prompt: "Turning a failed 5m scalp into a multi-day hold is best described as:",
    options: [
      "Style drift — usually hope, not a plan",
      "A required skill for prop firms",
      "Always the profitable way to manage losers",
      "How Fibonacci levels are drawn",
    ],
    correctIndex: 0,
  },
  {
    id: "c19",
    lessonId: "market-structure",
    prompt: "When price spikes through an obvious high then quickly reclaims, ask whether:",
    options: [
      "Stops/liquidity were grabbed rather than a clean breakout",
      "Structure no longer exists on any timeframe",
      "You must always double size into the spike",
      "Mark price is disabled",
    ],
    correctIndex: 0,
  },
  {
    id: "c20",
    lessonId: "novastaris-workflow",
    prompt: "Green AI scores on NovaStaris should:",
    options: [
      "Never override a broken thesis or missing invalidation",
      "Always mean you must buy immediately",
      "Replace stop-losses entirely",
      "Guarantee a funded prop account",
    ],
    correctIndex: 0,
  },
  {
    id: "c21",
    lessonId: "solana",
    prompt: "What is one practical benefit of Solana's low fees for small traders?",
    options: [
      "Small swaps and tests can be more economical",
      "Every token becomes risk-free",
      "Private keys are no longer needed",
      "Liquidation cannot occur on any exchange",
    ],
    correctIndex: 0,
  },
  {
    id: "c22",
    lessonId: "solana",
    prompt: "Which tool is commonly used to inspect Solana transactions and token accounts?",
    options: [
      "A Solana block explorer",
      "A forex economic calendar only",
      "A futures funding calculator only",
      "A prediction market resolver",
    ],
    correctIndex: 0,
  },
  {
    id: "c23",
    lessonId: "solana",
    prompt: "Why can a Solana transaction still fail even if the wallet has SOL?",
    options: [
      "Slippage, account state, congestion, or program rules can reject it",
      "SOL wallets cannot sign swaps",
      "All Solana transactions are manually approved by a bank",
      "Transactions only process once per day",
    ],
    correctIndex: 0,
  },
  {
    id: "c24",
    lessonId: "solana-memes",
    prompt: "Why can launchpad charts on Solana change quickly in the first minutes?",
    options: [
      "Buy pressure, bots, and low starting liquidity can move prices rapidly",
      "The price is fixed by the token name",
      "Only one wallet may trade at a time",
      "Stablecoins decide the opening price after a week",
    ],
    correctIndex: 0,
  },
  {
    id: "c25",
    lessonId: "solana-memes",
    prompt: "What should a trader verify before buying a Solana meme from a social link?",
    options: [
      "That the mint address matches the intended token",
      "That the token has no public holders",
      "That SOL gas is exactly zero",
      "That the creator promises a 100x return",
    ],
    correctIndex: 0,
  },
  {
    id: "c26",
    lessonId: "solana-memes",
    prompt: "What is one risk of competing with bots in Solana meme launches?",
    options: [
      "Humans may receive worse entries or exits in a fast-moving order flow",
      "Bots make every token audited",
      "Bots prevent all rugs from happening",
      "Bots convert SOL into forex lots",
    ],
    correctIndex: 0,
  },
  {
    id: "c27",
    lessonId: "bsc-memes",
    prompt: "Why is a honeypot check especially important before buying a BSC meme token?",
    options: [
      "Some malicious contracts allow buys while blocking or punishing sells",
      "It calculates the exact next Bitcoin halving date",
      "It guarantees the team cannot market the token",
      "It confirms the token is listed on every CEX",
    ],
    correctIndex: 0,
  },
  {
    id: "c28",
    lessonId: "forex",
    prompt: "Rule of thumb on EUR/USD: 0.10 lot ≈ $1 per pip, so 20 pips of risk is about:",
    options: [
      "$20 before spread",
      "$2 before spread",
      "$200 before spread",
      "$0.20 before spread",
    ],
    correctIndex: 0,
  },
  {
    id: "c29",
    lessonId: "bsc-memes",
    prompt: "Why do traders look at liquidity depth on PancakeSwap-style pools?",
    options: [
      "It affects slippage and whether exits can absorb sell pressure",
      "It determines the pip size of EUR/USD",
      "It makes a seed phrase public",
      "It decides the stablecoin reserve audit",
    ],
    correctIndex: 0,
  },
  {
    id: "c30",
    lessonId: "crypto-futures",
    prompt: "If BTC moves 2% against a 20x leveraged position, why is the risk severe?",
    options: [
      "The loss relative to margin can be large enough to approach liquidation",
      "The position automatically becomes a spot BTC holding",
      "The exchange must refund the funding payment",
      "The trader earns 20 pips by default",
    ],
    correctIndex: 0,
  },
  {
    id: "c31",
    lessonId: "crypto-futures",
    prompt: "What does liquidation price estimate?",
    options: [
      "The price where the exchange may force-close the position due to insufficient margin",
      "The guaranteed profit target of the trade",
      "The average price of all CEX listings",
      "The stablecoin peg level",
    ],
    correctIndex: 0,
  },
  {
    id: "c32",
    lessonId: "crypto-futures",
    prompt: "Cross margin’s main contagion risk is:",
    options: [
      "Shared wallet equity backs multiple positions — one loser can threaten the rest",
      "Cross margin bans stop-loss orders",
      "Cross margin makes funding always zero",
      "Cross margin converts shorts into spot holdings",
    ],
    correctIndex: 0,
  },
  {
    id: "c33",
    lessonId: "crypto-futures",
    prompt: "Mark price on perps is best described as:",
    options: [
      "An index/fair price many venues use for liquidation and unrealized PnL math",
      "Always identical to the last trade on your chart",
      "The overnight forex swap only",
      "A Solana priority tip",
    ],
    correctIndex: 0,
  },
  {
    id: "c34",
    lessonId: "predictions",
    prompt: "What does buying No in a prediction market express?",
    options: [
      "A view that the stated event will not happen under the market rules",
      "A short position on Bitcoin with leverage",
      "A claim on every possible outcome",
      "A guaranteed refund if the event is delayed",
    ],
    correctIndex: 0,
  },
  {
    id: "c35",
    lessonId: "predictions",
    prompt: "Why can liquidity be a risk in prediction markets?",
    options: [
      "A trader may be unable to enter or exit size near the displayed price",
      "Resolution rules become invalid when volume is low",
      "Low liquidity guarantees better fills",
      "Markets with low liquidity cannot settle",
    ],
    correctIndex: 0,
  },
  {
    id: "c36",
    lessonId: "predictions",
    prompt: "If you think an event has a 30% chance but Yes trades at 60 cents, what is the basic concern?",
    options: [
      "The market price may be too expensive relative to your estimate",
      "The market is automatically risk-free",
      "The No side cannot be purchased",
      "The market will pay out in pips",
    ],
    correctIndex: 0,
  },
  {
    id: "c37",
    lessonId: "forex",
    prompt: "What does EUR/USD = 1.0900 mean?",
    options: [
      "One euro is priced at 1.0900 US dollars",
      "One dollar is priced at 1.0900 euros",
      "EUR is the quote currency",
      "The pair moved exactly one pip today",
    ],
    correctIndex: 0,
  },
  {
    id: "c38",
    lessonId: "orders-execution",
    prompt: "Take-profit orders are used mainly to:",
    options: [
      "Lock gains at a planned target (or scale out in parts)",
      "Hide your seed phrase",
      "Increase leverage automatically",
      "Delete open interest",
    ],
    correctIndex: 0,
  },
  {
    id: "c39",
    lessonId: "chart-basics",
    prompt: "Double top / double bottom patterns are typically:",
    options: [
      "Potential reversal ideas if the neckline breaks with follow-through",
      "Guaranteed wins with no stop needed",
      "Only valid on forex exotics",
      "The same as a market order",
    ],
    correctIndex: 0,
  },
  {
    id: "c40",
    lessonId: "orders-execution",
    prompt: "Reduce-only on futures helps you:",
    options: [
      "Avoid accidentally flipping or increasing a position when you only meant to exit",
      "Skip stop-losses forever",
      "Guarantee maker rebates on every fill",
      "Turn memes into stablecoins",
    ],
    correctIndex: 0,
  },
];
