import type { UniversityQuizQuestion } from "./quiz";

/** Extra 20 questions for Set A (40 → 60). */
export const EXAM_SET_A_EXTRA: UniversityQuizQuestion[] = [
  {
    id: "a41",
    lessonId: "ethereum-l2s",
    prompt: "A common bridge risk when moving funds to an L2 is:",
    options: [
      "Using a fake bridge UI or wrong contract and losing the transfer",
      "Automatically earning infinite gas refunds",
      "Converting your seed into a stablecoin",
      "Guaranteed same-block finality on every chain",
    ],
    correctIndex: 0,
  },
  {
    id: "a42",
    lessonId: "ethereum-l2s",
    prompt: "Same ticker on ETH mainnet vs an L2 usually means:",
    options: [
      "Different contracts — always verify chain and address before buying",
      "Identical tokens with automatic bridging",
      "The L2 copy is always the “real” one",
      "Gas is free so scams are impossible",
    ],
    correctIndex: 0,
  },
  {
    id: "a43",
    lessonId: "options-volatility",
    prompt: "Buying a call option means you:",
    options: [
      "Pay premium for the right (not obligation) to benefit if price rises enough",
      "Must buy the asset at market no matter what",
      "Earn funding like a perp long",
      "Have unlimited time with zero decay",
    ],
    correctIndex: 0,
  },
  {
    id: "a44",
    lessonId: "options-volatility",
    prompt: "You can be right on direction and still lose on a long option mainly because of:",
    options: [
      "Time decay / insufficient move relative to what you paid in premium",
      "Forced funding payments every 8 hours on all listed options",
      "Automatic conversion into spot at midnight",
      "Options never expire",
    ],
    correctIndex: 0,
  },
  {
    id: "a45",
    lessonId: "advanced-markets",
    prompt: "Rising open interest with a strong trend often suggests:",
    options: [
      "New leveraged positioning is adding fuel — trend can extend or unwind violently",
      "That funding is always zero",
      "That spot holders cannot sell",
      "That liquidation maps are irrelevant",
    ],
    correctIndex: 0,
  },
  {
    id: "a46",
    lessonId: "advanced-markets",
    prompt: "A tokenomics red flag before a narrative pitch is often:",
    options: [
      "Huge unlocked insider/team supply ready to dump into liquidity",
      "A documented vesting schedule with transparent unlocks",
      "Clear utility and on-chain revenue",
      "Verified contracts and audited team wallets",
    ],
    correctIndex: 0,
  },
  {
    id: "a47",
    lessonId: "volume-vwap",
    prompt: "VWAP is commonly used as:",
    options: [
      "An intraday volume-weighted average price benchmark institutions often respect",
      "A wallet seed recovery phrase",
      "A perpetual funding formula on every chain",
      "A guarantee of next-day direction",
    ],
    correctIndex: 0,
  },
  {
    id: "a48",
    lessonId: "volume-vwap",
    prompt: "A breakout with very thin volume versus prior bars is often:",
    options: [
      "Less trustworthy — weak participation can fail quicker",
      "Proof institutions are all-in",
      "A reason to 10× immediately",
      "Irrelevant to chart structure",
    ],
    correctIndex: 0,
  },
  {
    id: "a49",
    lessonId: "trading-styles",
    prompt: "Swing trading typically holds:",
    options: [
      "Days to weeks — wider stops and less need to watch every tick",
      "Seconds only — always market-close same candle",
      "Forever with no invalidation",
      "Only while funding is negative",
    ],
    correctIndex: 0,
  },
  {
    id: "a50",
    lessonId: "trading-styles",
    prompt: "Matching style to lifestyle mainly means:",
    options: [
      "Your hold time and screen time fit how you actually live and work",
      "Copying the noisiest trader on social media",
      "Always using max leverage available",
      "Ignoring risk because the style is “advanced”",
    ],
    correctIndex: 0,
  },
  {
    id: "a51",
    lessonId: "backtesting-expectancy",
    prompt: "Expectancy answers:",
    options: [
      "Average $ (or R) you expect per trade over a large sample",
      "Whether one anecdotal win proves edge",
      "Tomorrow’s exact open",
      "Your exchange’s referral rebate",
    ],
    correctIndex: 0,
  },
  {
    id: "a52",
    lessonId: "backtesting-expectancy",
    prompt: "Curve-fitting a strategy until history looks perfect often leads to:",
    options: [
      "Poor live results when conditions change",
      "Guaranteed forward profit",
      "Zero slippage forever",
      "Free funding on every long",
    ],
    correctIndex: 0,
  },
  {
    id: "a53",
    lessonId: "meme-trading",
    prompt: "Sizing a meme entry relative to tips/fees means:",
    options: [
      "Bribe/tip + fees should not eat a huge % of your intended notional",
      "Tips replace the need for a stop",
      "You should tip more than the buy size always",
      "Fees only apply after you 10×",
    ],
    correctIndex: 0,
  },
  {
    id: "a54",
    lessonId: "risk-fundamentals",
    prompt: "An R-multiple describes:",
    options: [
      "Profit or loss in units of initial planned risk (e.g. +2R)",
      "Your account’s KYC level",
      "The exchange maker fee only",
      "Candlestick wick color",
    ],
    correctIndex: 0,
  },
  {
    id: "a55",
    lessonId: "crypto-futures",
    prompt: "Basis (perp vs spot) can matter because:",
    options: [
      "Large premium/discount affects carry and whether perps are “rich” vs spot",
      "It deletes liquidation risk",
      "It sets your KYC country",
      "It fixes funding at zero forever",
    ],
    correctIndex: 0,
  },
  {
    id: "a56",
    lessonId: "market-structure",
    prompt: "Higher-timeframe bias first, then lower-timeframe entry mainly helps:",
    options: [
      "Avoid fighting the bigger trend while refining timing",
      "Ignore invalidation levels",
      "Remove the need for risk management",
      "Guarantee fills at VWAP",
    ],
    correctIndex: 0,
  },
  {
    id: "a57",
    lessonId: "orders-execution",
    prompt: "A stop-loss order’s primary job is:",
    options: [
      "Cap loss when price hits your invalidation — not to “predict” reverse profits",
      "Guarantee a better average entry",
      "Cancel funding payments",
      "Replace position sizing",
    ],
    correctIndex: 0,
  },
  {
    id: "a58",
    lessonId: "psychology-journaling",
    prompt: "A daily loss limit is most useful when you:",
    options: [
      "Treat it as a hard stop-day to prevent tilt spiral",
      "Raise it after each loss to “get even”",
      "Ignore it on meme coins only",
      "Replace it with doubling size",
    ],
    correctIndex: 0,
  },
  {
    id: "a59",
    lessonId: "novastaris-workflow",
    prompt: "A healthy NovaStaris flow for memes starts with:",
    options: [
      "Discovery/filters → thesis check → defined size/risk → only then click buy",
      "Max size on the first green candle you see",
      "Skipping security checks if the chart is pretty",
      "Ignoring fees because AI said “bullish”",
    ],
    correctIndex: 0,
  },
  {
    id: "a60",
    lessonId: "wallets-security",
    prompt: "Approving unlimited spend for a random dApp is risky because:",
    options: [
      "A malicious contract can drain tokens later without another signature",
      "Approvals always expire in one block",
      "CEX deposits use the same approval popup",
      "Gas fees refund the approval automatically",
    ],
    correctIndex: 0,
  },
];

/** Extra 20 questions for Set B (40 → 60). */
export const EXAM_SET_B_EXTRA: UniversityQuizQuestion[] = [
  {
    id: "b41",
    lessonId: "ethereum-l2s",
    prompt: "Lower fees on an L2 do not remove the need to:",
    options: [
      "Verify you’re on the intended chain and contract before sizing up",
      "Always use 100× leverage",
      "Disable hardware wallets forever",
      "Ignore phishing because L2s are “safe”",
    ],
    correctIndex: 0,
  },
  {
    id: "b42",
    lessonId: "ethereum-l2s",
    prompt: "Withdrawals/bridging delays are most dangerous when:",
    options: [
      "You assume instant unwind and size as if exits are always immediate",
      "You leave dust on the L2",
      "You use an official documented bridge carefully",
      "You keep a hot-wallet budget for gas",
    ],
    correctIndex: 0,
  },
  {
    id: "b43",
    lessonId: "options-volatility",
    prompt: "A put buyer generally wants:",
    options: [
      "Price to fall enough (or vol to jump) to beat premium paid",
      "Unlimited obligatory short inventory",
      "Positive funding every hour with no expiry",
      "To mint the underlying for free",
    ],
    correctIndex: 0,
  },
  {
    id: "b44",
    lessonId: "options-volatility",
    prompt: "Implied volatility rising, all else equal, tends to:",
    options: [
      "Make option premiums more expensive",
      "Delete theta entirely",
      "Force all options to expire worthless instantly",
      "Set funding to zero on perps only",
    ],
    correctIndex: 0,
  },
  {
    id: "b45",
    lessonId: "advanced-markets",
    prompt: "Prop-firm style rules often blow accounts via:",
    options: [
      "Trailing/drawdown limits and daily loss caps that ignore “I was almost right”",
      "Unlimited free retries with no risk limits",
      "Mandatory 1:1 spot-only trading",
      "No leverage available at all",
    ],
    correctIndex: 0,
  },
  {
    id: "b46",
    lessonId: "advanced-markets",
    prompt: "Crowded positioning shows up most clearly in:",
    options: [
      "Open interest, funding extremes, and liquidation cascades",
      "Your desktop wallpaper color",
      "Exchange referral codes",
      "Candle body fonts",
    ],
    correctIndex: 0,
  },
  {
    id: "b47",
    lessonId: "volume-vwap",
    prompt: "Trading back toward VWAP from an extended move is often about:",
    options: [
      "Mean-reversion toward an institutional benchmark — not guaranteed",
      "Guaranteed continuation away from VWAP forever",
      "Canceling the need for a stop",
      "Ignoring session open entirely",
    ],
    correctIndex: 0,
  },
  {
    id: "b48",
    lessonId: "volume-vwap",
    prompt: "Volume profile “value” areas roughly describe:",
    options: [
      "Price regions where a lot of volume traded — acceptance zones",
      "Your wallet’s seed word list",
      "Only futures funding timestamps",
      "The exchange’s API rate limits",
    ],
    correctIndex: 0,
  },
  {
    id: "b49",
    lessonId: "trading-styles",
    prompt: "Scalping typically requires:",
    options: [
      "Tight risk, fast decisions, and costs that don’t erase tiny targets",
      "Multi-week holds with wide weekly chart stops only",
      "Ignoring spreads because holds are short",
      "No invalidation if news hits",
    ],
    correctIndex: 0,
  },
  {
    id: "b50",
    lessonId: "trading-styles",
    prompt: "Using a scalp stop with a swing thesis is usually a problem because:",
    options: [
      "Normal noise stops you out before the bigger idea can play",
      "It always improves expectancy",
      "Funding becomes negative automatically",
      "Exchanges ban mixed timeframes",
    ],
    correctIndex: 0,
  },
  {
    id: "b51",
    lessonId: "backtesting-expectancy",
    prompt: "A tiny sample of winning trades proves:",
    options: [
      "Almost nothing — variance can fake an edge",
      "Guaranteed live profitability",
      "That fees don’t matter",
      "That leverage should be maximized",
    ],
    correctIndex: 0,
  },
  {
    id: "b52",
    lessonId: "backtesting-expectancy",
    prompt: "Including fees and slippage in backtests matters because:",
    options: [
      "Optimistic fills can turn a “winning” system into a loser live",
      "Fees only apply to losing trades",
      "Slippage always improves your entry",
      "Exchanges refund all backtested fees",
    ],
    correctIndex: 0,
  },
  {
    id: "b53",
    lessonId: "meme-coins",
    prompt: "Meme narrative velocity matters because:",
    options: [
      "Attention drives flows — culture can move price faster than fundamentals",
      "Memes always have audited treasuries",
      "Narratives remove rug risk",
      "On-chain holders cannot sell during narratives",
    ],
    correctIndex: 0,
  },
  {
    id: "b54",
    lessonId: "solana-memes",
    prompt: "Early bonding-curve risk vs post-migrate risk differs mainly in:",
    options: [
      "Liquidity depth, exit mechanics, and sniper/competition dynamics",
      "Whether SOL exists",
      "Whether candles can print",
      "Whether wallets need seed phrases",
    ],
    correctIndex: 0,
  },
  {
    id: "b55",
    lessonId: "bsc-memes",
    prompt: "A honeypot-style trap often shows up as:",
    options: [
      "You can buy but cannot sell (or sell tax is extreme)",
      "Chart volume is always green",
      "Gas is cheaper than Ethereum",
      "The ticker matches a famous brand",
    ],
    correctIndex: 0,
  },
  {
    id: "b56",
    lessonId: "crypto-futures",
    prompt: "Isolated margin primarily limits:",
    options: [
      "How much of the account that position can liquidate",
      "Whether you can set a take-profit",
      "Candle timeframe options",
      "Whether funding exists",
    ],
    correctIndex: 0,
  },
  {
    id: "b57",
    lessonId: "predictions",
    prompt: "A prediction-market price near 0.70 roughly implies:",
    options: [
      "~70% market-implied probability of that outcome (before fees)",
      "A guaranteed 70% ROI",
      "That the event already resolved yes",
      "That leverage is 70×",
    ],
    correctIndex: 0,
  },
  {
    id: "b58",
    lessonId: "forex",
    prompt: "Trading overlapping London/NY sessions often means:",
    options: [
      "Higher liquidity and more movement — both opportunity and noise",
      "Markets are closed worldwide",
      "Spreads are always widest of the day",
      "Swaps are disabled for all pairs",
    ],
    correctIndex: 0,
  },
  {
    id: "b59",
    lessonId: "intro-crypto",
    prompt: "CEX vs DEX mainly differs in:",
    options: [
      "Custody and matching — CEX holds balances; DEX trades from your wallet",
      "Whether BTC can be priced in USD",
      "Whether candles can form",
      "Whether leverage always exists",
    ],
    correctIndex: 0,
  },
  {
    id: "b60",
    lessonId: "chart-basics",
    prompt: "Multi-timeframe analysis means:",
    options: [
      "Read higher TF context, then refine with lower TF entries",
      "Only trade the 1-minute chart forever",
      "Ignore HTF levels once you zoom in",
      "Average all timeframes into one candle",
    ],
    correctIndex: 0,
  },
];

/** Extra 20 questions for Set C (40 → 60). */
export const EXAM_SET_C_EXTRA: UniversityQuizQuestion[] = [
  {
    id: "c41",
    lessonId: "ethereum-l2s",
    prompt: "“Cheap gas” on an L2 is most misleading when:",
    options: [
      "You still oversize into an illiquid scam token and cannot exit cleanly",
      "You pay a few cents to transfer USDC on a known rollup",
      "You bridge small test amounts first",
      "You verify the official chain ID",
    ],
    correctIndex: 0,
  },
  {
    id: "c42",
    lessonId: "options-volatility",
    prompt: "Compared with perps, long options risk is often capped near:",
    options: [
      "The premium you paid (if you only buy options)",
      "Infinite margin calls identical to 100× perps",
      "Your entire CEX account via cross funding only",
      "Zero — options cannot lose money",
    ],
    correctIndex: 0,
  },
  {
    id: "c43",
    lessonId: "options-volatility",
    prompt: "Selling naked options can be dangerous because:",
    options: [
      "Losses can far exceed the premium collected",
      "Theta always pays you with no risk",
      "Exchanges refund assignment losses",
      "IV crush cannot hurt sellers",
    ],
    correctIndex: 0,
  },
  {
    id: "c44",
    lessonId: "advanced-markets",
    prompt: "Funding extremes often mean:",
    options: [
      "One side is crowded — squeezes and mean reversion in funding can follow",
      "Price cannot reverse",
      "Liquidation is impossible",
      "Spot and perp are identical always",
    ],
    correctIndex: 0,
  },
  {
    id: "c45",
    lessonId: "advanced-markets",
    prompt: "Opaque unlock schedules are a risk because:",
    options: [
      "Large sudden supply can hit thin liquidity and crash price",
      "Unlocks always buy the token",
      "Vesting eliminates all volatility",
      "Team tokens cannot transfer on-chain",
    ],
    correctIndex: 0,
  },
  {
    id: "c46",
    lessonId: "volume-vwap",
    prompt: "Price holding above VWAP in a strong up session often reads as:",
    options: [
      "Buyers defending the session average — until it fails",
      "Proof shorts are banned",
      "A reason to abandon stops",
      "That volume profile is unused",
    ],
    correctIndex: 0,
  },
  {
    id: "c47",
    lessonId: "trading-styles",
    prompt: "Position trading holds:",
    options: [
      "Weeks to months — thesis and macro matter more than ticks",
      "Only the current 1-second candle",
      "Until funding flips once",
      "Without ever defining risk",
    ],
    correctIndex: 0,
  },
  {
    id: "c48",
    lessonId: "backtesting-expectancy",
    prompt: "A nice equity curve on optimized parameters may fail live due to:",
    options: [
      "Overfitting and regime change",
      "Too many out-of-sample tests",
      "Including realistic fees",
      "Using walk-forward validation",
    ],
    correctIndex: 0,
  },
  {
    id: "c49",
    lessonId: "market-structure",
    prompt: "A liquidity grab that reverses often looks like:",
    options: [
      "Sweep beyond obvious highs/lows then sharp reclaim the other way",
      "Price consolidating politely for weeks with no wicks",
      "Funding printing exactly zero",
      "Volume disappearing forever",
    ],
    correctIndex: 0,
  },
  {
    id: "c50",
    lessonId: "crypto-futures",
    prompt: "Higher leverage mainly:",
    options: [
      "Moves liquidation closer — same thesis, less cushion for noise",
      "Removes funding payments",
      "Guarantees higher expectancy",
      "Converts the perp into spot automatically",
    ],
    correctIndex: 0,
  },
  {
    id: "c51",
    lessonId: "meme-trading",
    prompt: "FOMO size after a vertical green candle usually fails because:",
    options: [
      "You’re late, liquidity is worse, and risk/reward is already distorted",
      "Green candles cannot reverse",
      "Tips become free after pumps",
      "Stop losses do not work on memes",
    ],
    correctIndex: 0,
  },
  {
    id: "c52",
    lessonId: "risk-fundamentals",
    prompt: "Position size from a $ stop is mainly:",
    options: [
      "Risk $ ÷ distance-to-stop (in $ per unit) so loss matches plan",
      "Always 100% of the account",
      "Ignoring the stop and using hope",
      "Matching your friend’s size",
    ],
    correctIndex: 0,
  },
  {
    id: "c53",
    lessonId: "orders-execution",
    prompt: "Chasing with market orders into thin books primarily risks:",
    options: [
      "Worse average fill / slippage than a planned limit",
      "Guaranteed better entry than makers",
      "Zero fees on every venue",
      "Automatic stop placement for free",
    ],
    correctIndex: 0,
  },
  {
    id: "c54",
    lessonId: "psychology-journaling",
    prompt: "A useful trade journal entry includes:",
    options: [
      "Plan, size, emotions, outcome, and what you’ll change next time",
      "Only the PnL emoji",
      "Screenshots with no notes",
      "Other people’s bag sizes only",
    ],
    correctIndex: 0,
  },
  {
    id: "c55",
    lessonId: "predictions",
    prompt: "Your edge in prediction markets comes from:",
    options: [
      "A better probability estimate than the market price implies — after fees",
      "Always buying the favorite near 0.95",
      "Ignoring resolution rules",
      "Treating every market like a meme coin chart",
    ],
    correctIndex: 0,
  },
  {
    id: "c56",
    lessonId: "forex",
    prompt: "Pip value scales with:",
    options: [
      "Lot size (and pair) — larger size means more $ per pip",
      "How many Twitter followers you have",
      "Whether BTC is green that day only",
      "Your monitor refresh rate",
    ],
    correctIndex: 0,
  },
  {
    id: "c57",
    lessonId: "solana",
    prompt: "Solana meme culture is fast partly because:",
    options: [
      "Low fees and quick confirms let launch/trade loops run quickly",
      "There is no risk of rugs",
      "Wallets cannot be drained",
      "Validators publish free trading signals",
    ],
    correctIndex: 0,
  },
  {
    id: "c58",
    lessonId: "novastaris-workflow",
    prompt: "Using Go Hunting then AI analysis without a risk plan is incomplete because:",
    options: [
      "Signal quality still needs size, invalidation, and exit rules",
      "AI always places stops for you",
      "Tools remove variance",
      "Discovery tabs ban losing trades",
    ],
    correctIndex: 0,
  },
  {
    id: "c59",
    lessonId: "wallets-security",
    prompt: "A cold wallet’s main security advantage is:",
    options: [
      "Private keys stay offline more of the time vs hot wallets",
      "It cannot receive phishing tokens",
      "It makes all dApps safe",
      "It removes the need to verify addresses",
    ],
    correctIndex: 0,
  },
  {
    id: "c60",
    lessonId: "intro-crypto",
    prompt: "Stablecoins are useful but not risk-free mainly because of:",
    options: [
      "Issuer, banking, and depeg risk historically seen in crypto",
      "They cannot be transferred on-chain",
      "They always print at $2",
      "Exchanges refuse to list them",
    ],
    correctIndex: 0,
  },
];
