import type { UniversityQuizQuestion } from "./quiz";

export const EXAM_SET_B: UniversityQuizQuestion[] = [
  {
    id: "b1",
    lessonId: "intro-crypto",
    prompt: "Why is Bitcoin often treated as the reference asset for the crypto market?",
    options: [
      "It is the oldest major crypto network and largest liquidity benchmark",
      "It is issued by the Federal Reserve",
      "It is a stablecoin designed to stay at $1",
      "It can only be traded on decentralized exchanges",
    ],
    correctIndex: 0,
  },
  {
    id: "b2",
    lessonId: "chart-basics",
    prompt: "What do OHLC stand for on a candlestick?",
    options: [
      "Open, High, Low, Close",
      "Order, Hedge, Lot, Contract",
      "Only High Liquidity Candles",
      "Overnight Holding Limit Cost",
    ],
    correctIndex: 0,
  },
  {
    id: "b3",
    lessonId: "chart-basics",
    prompt: "Wicks (shadows) on a candle show:",
    options: [
      "The period’s extreme high and low beyond the body",
      "Only the exchange’s funding rate",
      "Your broker’s swap fee",
      "The exact liquidation price of every trader",
    ],
    correctIndex: 0,
  },
  {
    id: "b4",
    lessonId: "orders-execution",
    prompt: "A stop order (stop-market) typically:",
    options: [
      "Becomes a market order when a trigger price is hit",
      "Fills only at your limit price forever",
      "Deletes funding rates",
      "Locks Fib levels on the chart",
    ],
    correctIndex: 0,
  },
  {
    id: "b5",
    lessonId: "wallets-security",
    prompt: "What is the safest assumption when a website asks for your recovery phrase?",
    options: [
      "It is likely malicious, because legitimate apps do not need the phrase",
      "It is required for every normal token swap",
      "It only proves wallet ownership and cannot move funds",
      "It is safe if the website has a polished logo",
    ],
    correctIndex: 0,
  },
  {
    id: "b6",
    lessonId: "wallets-security",
    prompt: "Why should token approvals be reviewed after trading risky meme coins?",
    options: [
      "Some approvals can let contracts move tokens later if left unlimited",
      "Approvals automatically create a stop-loss order",
      "Approvals prevent all honeypots from working",
      "Approvals convert hot wallets into cold wallets",
    ],
    correctIndex: 0,
  },
  {
    id: "b7",
    lessonId: "wallets-security",
    prompt: "A hardware wallet mainly improves security by:",
    options: [
      "Keeping signing keys isolated from the internet-connected computer",
      "Making every transaction free",
      "Increasing leverage limits on futures exchanges",
      "Hiding public wallet balances from block explorers",
    ],
    correctIndex: 0,
  },
  {
    id: "b8",
    lessonId: "wallets-security",
    prompt: "What is a practical reason to keep a small trading wallet separate from long-term holdings?",
    options: [
      "It limits damage if a risky site, approval, or hot wallet is compromised",
      "It makes losing the seed phrase impossible",
      "It guarantees every meme coin can be sold",
      "It removes the need to pay network fees",
    ],
    correctIndex: 0,
  },
  {
    id: "b9",
    lessonId: "risk-fundamentals",
    prompt: "A trader risking 1% per setup is primarily controlling:",
    options: [
      "The maximum planned account damage if the idea is wrong",
      "The exact profit target the market must reach",
      "The exchange's liquidation engine",
      "The number of followers a token account receives",
    ],
    correctIndex: 0,
  },
  {
    id: "b10",
    lessonId: "risk-fundamentals",
    prompt: "Why does a stop level belong in the plan before entering a position?",
    options: [
      "It defines where the trade thesis is no longer valid",
      "It guarantees a fill with no slippage",
      "It forces the trade to close in profit",
      "It removes fees from the execution",
    ],
    correctIndex: 0,
  },
  {
    id: "b11",
    lessonId: "risk-fundamentals",
    prompt: "Which habit usually reduces blow-up risk during a losing streak?",
    options: [
      "Reducing size or pausing instead of doubling down emotionally",
      "Increasing leverage after every loss",
      "Ignoring the original invalidation level",
      "Moving all funds into one launch token",
    ],
    correctIndex: 0,
  },
  {
    id: "b12",
    lessonId: "risk-fundamentals",
    prompt: "What does risk-to-reward compare?",
    options: [
      "The amount at risk versus the realistic upside target",
      "The bid price versus the ask price only",
      "The number of wallet addresses versus holders",
      "The stablecoin supply versus Bitcoin supply",
    ],
    correctIndex: 0,
  },
  {
    id: "b13",
    lessonId: "meme-coins",
    prompt: "Why can meme coins move violently without news about revenue or products?",
    options: [
      "Attention, narrative, and liquidity can dominate fundamentals",
      "They are all backed by insured bank deposits",
      "They settle only once per month",
      "Their prices are fixed by validators",
    ],
    correctIndex: 0,
  },
  {
    id: "b14",
    lessonId: "meme-coins",
    prompt: "Which holder pattern is a red flag for a new meme token?",
    options: [
      "A few wallets control a large share of supply",
      "Many small wallets hold tiny balances",
      "The token has a public chart",
      "The token trades against a stablecoin pair",
    ],
    correctIndex: 0,
  },
  {
    id: "b15",
    lessonId: "meme-coins",
    prompt: "A liquidity lock or burned LP is checked because it can show whether:",
    options: [
      "The team can easily pull pool liquidity",
      "The token will always trend on social media",
      "The chart must keep rising",
      "The contract has no buy tax",
    ],
    correctIndex: 0,
  },
  {
    id: "b16",
    lessonId: "meme-coins",
    prompt: "What makes a meme coin community useful to evaluate?",
    options: [
      "It can reveal organic interest versus bots, spam, or paid hype",
      "It proves the contract cannot be malicious",
      "It sets the official Bitcoin mining reward",
      "It removes the need for position sizing",
    ],
    correctIndex: 0,
  },
  {
    id: "b17",
    lessonId: "meme-trading",
    prompt: "In a fast meme launch, why can a high slippage setting be dangerous?",
    options: [
      "It may allow a much worse fill than expected",
      "It prevents the transaction from ever confirming",
      "It guarantees priority over every other trader",
      "It automatically audits the contract",
    ],
    correctIndex: 0,
  },
  {
    id: "b18",
    lessonId: "meme-trading",
    prompt: "What is the trading purpose of a Jito tip during a crowded Solana launch?",
    options: [
      "To improve the chance of landing the transaction quickly",
      "To pay the token creator's income tax",
      "To remove the risk of liquidation",
      "To peg the token price to USDC",
    ],
    correctIndex: 0,
  },
  {
    id: "b19",
    lessonId: "meme-trading",
    prompt: "Why are partial exits common in volatile meme trades?",
    options: [
      "They can lock in some gains while leaving upside exposure",
      "They guarantee the remaining position cannot lose value",
      "They cancel all network fees already paid",
      "They make honeypots sellable",
    ],
    correctIndex: 0,
  },
  {
    id: "b20",
    lessonId: "meme-trading",
    prompt: "What does chasing a candle usually mean?",
    options: [
      "Entering after a sharp move from fear of missing out",
      "Buying only after a written invalidation is hit",
      "Waiting for liquidity to deepen before trading",
      "Reducing risk after a large win",
    ],
    correctIndex: 0,
  },
  {
    id: "b21",
    lessonId: "solana",
    prompt: "What does SOL pay for when you submit a normal transaction?",
    options: [
      "Network fees and, when chosen, priority fees",
      "A guaranteed listing on every CEX",
      "The token's future marketing budget",
      "The forex broker spread",
    ],
    correctIndex: 0,
  },
  {
    id: "b22",
    lessonId: "solana",
    prompt: "Why do traders often verify a Solana mint address before swapping?",
    options: [
      "Similar token names can point to completely different assets",
      "The mint address reveals the trader's seed phrase",
      "A verified mint removes all price volatility",
      "Only fake tokens have mint addresses",
    ],
    correctIndex: 0,
  },
  {
    id: "b23",
    lessonId: "solana",
    prompt: "What is a common reason Solana users increase priority fees during congestion?",
    options: [
      "To compete for faster transaction inclusion",
      "To permanently lower token taxes",
      "To turn a DEX swap into a CEX order",
      "To reduce the circulating supply of Bitcoin",
    ],
    correctIndex: 0,
  },
  {
    id: "b24",
    lessonId: "solana-memes",
    prompt: "In many Solana meme launches, what happens when a bonding curve completes?",
    options: [
      "Liquidity may migrate to a DEX pool for open trading",
      "The token becomes a fiat bank account",
      "All early buyers are liquidated",
      "The project automatically receives a patent",
    ],
    correctIndex: 0,
  },
  {
    id: "b25",
    lessonId: "solana-memes",
    prompt: "Why is early Solana meme trading considered especially risky?",
    options: [
      "Projects may have little history, thin liquidity, and concentrated ownership",
      "SOL transactions cannot fail",
      "Every new token is backed by USDC",
      "Validators choose winners manually",
    ],
    correctIndex: 0,
  },
  {
    id: "b26",
    lessonId: "solana-memes",
    prompt: "What does a quick check of top holders help a Solana meme trader estimate?",
    options: [
      "Whether a few wallets could dump heavily into buyers",
      "The exact next funding payment",
      "The pip value of USD/JPY",
      "The official market resolution date",
    ],
    correctIndex: 0,
  },
  {
    id: "b27",
    lessonId: "bsc-memes",
    prompt: "A BSC honeypot is dangerous because a trader may be able to:",
    options: [
      "Buy the token but fail to sell it normally",
      "Sell the token without first buying it",
      "Avoid all tax and gas costs",
      "Convert BNB into Bitcoin mining rewards",
    ],
    correctIndex: 0,
  },
  {
    id: "b28",
    lessonId: "bsc-memes",
    prompt: "Why do BSC meme traders check buy and sell tax before entering?",
    options: [
      "High or changeable taxes can make exits much worse than expected",
      "Taxes determine the global Bitcoin hash rate",
      "A tax means the token is always audited",
      "A tax replaces the need for liquidity",
    ],
    correctIndex: 0,
  },
  {
    id: "b29",
    lessonId: "bsc-memes",
    prompt: "What role does BNB usually play in BSC meme trading?",
    options: [
      "It pays gas and is often paired with tokens for liquidity",
      "It is the native coin of Solana",
      "It is a forex base currency",
      "It settles prediction markets at expiration",
    ],
    correctIndex: 0,
  },
  {
    id: "b30",
    lessonId: "crypto-futures",
    prompt: "What happens to both gains and losses when a trader uses 10x leverage?",
    options: [
      "They are magnified relative to the margin posted",
      "Losses disappear but gains remain",
      "The position becomes spot ownership",
      "Funding payments can no longer occur",
    ],
    correctIndex: 0,
  },
  {
    id: "b31",
    lessonId: "crypto-futures",
    prompt: "Why can a small adverse move liquidate an overleveraged position?",
    options: [
      "The margin buffer is thin relative to the notional exposure",
      "The exchange converts every loss into USDC",
      "The order book stops accepting bids",
      "The trader owns the underlying coin outright",
    ],
    correctIndex: 0,
  },
  {
    id: "b32",
    lessonId: "crypto-futures",
    prompt: "What is the key difference between going long and going short on a perp?",
    options: [
      "A long benefits from price rising, while a short benefits from price falling",
      "A long pays no fees, while a short pays all fees",
      "A short can never be liquidated",
      "A long always owns the underlying token",
    ],
    correctIndex: 0,
  },
  {
    id: "b33",
    lessonId: "crypto-futures",
    prompt: "Why does funding exist in perpetual futures markets?",
    options: [
      "To help keep the contract price anchored near spot through payments between sides",
      "To guarantee all traders receive yield",
      "To pay Solana priority fees",
      "To fix the pip size of every forex pair",
    ],
    correctIndex: 0,
  },
  {
    id: "b34",
    lessonId: "predictions",
    prompt: "If a prediction market Yes share trades at 72 cents, what does that roughly imply?",
    options: [
      "The market is pricing about a 72% chance before fees and other frictions",
      "The event pays 72 Bitcoin if correct",
      "The trader is using 72x leverage",
      "The market will resolve in 72 minutes",
    ],
    correctIndex: 0,
  },
  {
    id: "b35",
    lessonId: "predictions",
    prompt: "Why should prediction traders read resolution criteria before betting?",
    options: [
      "The exact wording determines what outcome will settle the market",
      "It reveals the private key of the market creator",
      "It removes all liquidity risk",
      "It sets the spread on EUR/USD",
    ],
    correctIndex: 0,
  },
  {
    id: "b36",
    lessonId: "predictions",
    prompt: "A prediction market edge exists when:",
    options: [
      "Your estimated probability differs from the market price enough to overcome costs and risk",
      "You always buy the cheaper side",
      "The event is popular on social media",
      "The market has more than four answer options",
    ],
    correctIndex: 0,
  },
  {
    id: "b37",
    lessonId: "forex",
    prompt: "For most major pairs quoted to four decimals, one pip is:",
    options: ["0.0001", "0.01", "1.0000", "100 pips"],
    correctIndex: 0,
  },
  {
    id: "b38",
    lessonId: "chart-basics",
    prompt: "An uptrend line is typically drawn by connecting:",
    options: [
      "Rising swing lows",
      "Only funding rate dots",
      "Random open interest spikes",
      "Seed phrase words",
    ],
    correctIndex: 0,
  },
  {
    id: "b39",
    lessonId: "chart-basics",
    prompt: "A gravestone doji often shows:",
    options: [
      "Long upper wick with open/close near the low — rejection of highs",
      "Guaranteed continuation higher",
      "Zero volatility forever",
      "A locked LP on BSC",
    ],
    correctIndex: 0,
  },
  {
    id: "b40",
    lessonId: "orders-execution",
    prompt: "Why cancel open working orders when your thesis changes?",
    options: [
      "Stale limits/stops can fill and put you in an unwanted trade",
      "Exchanges ban accounts with open orders",
      "Working orders delete your journal",
      "Fib tools stop working if orders exist",
    ],
    correctIndex: 0,
  },
];

export const EXAM_SET_C: UniversityQuizQuestion[] = [
  {
    id: "c1",
    lessonId: "intro-crypto",
    prompt: "What makes a blockchain ledger different from a private spreadsheet?",
    options: [
      "Many network participants can verify updates under shared rules",
      "Only one bank employee can edit every balance",
      "It never needs cryptographic signatures",
      "It guarantees every listed token is safe",
    ],
    correctIndex: 0,
  },
  {
    id: "c2",
    lessonId: "chart-basics",
    prompt: "A chart timeframe (e.g. 5m or 1h) means:",
    options: [
      "How long each candle represents",
      "The broker’s overnight swap rate",
      "The number of pips in a lot",
      "Your account’s KYC tier",
    ],
    correctIndex: 0,
  },
  {
    id: "c3",
    lessonId: "chart-basics",
    prompt: "An engulfing candle is most useful when:",
    options: [
      "Its body fully covers the prior body and appears at an extreme — not mid-chop alone",
      "It appears anywhere and guarantees a 10× move",
      "It removes the need for a stop-loss",
      "It only appears on forex majors",
    ],
    correctIndex: 0,
  },
  {
    id: "c4",
    lessonId: "chart-basics",
    prompt: "A hammer candle is typically described as:",
    options: [
      "Small body near the high with a long lower wick — possible rejection of lows",
      "A funding payment from longs to shorts",
      "A guaranteed short signal",
      "An open limit order on the exchange",
    ],
    correctIndex: 0,
  },
  {
    id: "c5",
    lessonId: "wallets-security",
    prompt: "Which item is safe to share when receiving funds?",
    options: [
      "Your public wallet address",
      "Your seed phrase",
      "Your hardware wallet PIN",
      "Your private key",
    ],
    correctIndex: 0,
  },
  {
    id: "c6",
    lessonId: "wallets-security",
    prompt: "What is the risk of signing a transaction you do not understand?",
    options: [
      "You may authorize token transfers, approvals, or malicious actions",
      "It only changes your chart theme",
      "It creates a guaranteed arbitrage",
      "It prevents the transaction from reaching the network",
    ],
    correctIndex: 0,
  },
  {
    id: "c7",
    lessonId: "wallets-security",
    prompt: "Why is two-factor authentication useful on a CEX account?",
    options: [
      "It adds another barrier beyond the password",
      "It makes a seed phrase unnecessary for self-custody wallets",
      "It guarantees withdrawals can never be delayed",
      "It audits every token listed on the exchange",
    ],
    correctIndex: 0,
  },
  {
    id: "c8",
    lessonId: "wallets-security",
    prompt: "What should you do before connecting a wallet to an unfamiliar trading site?",
    options: [
      "Check the URL, permissions, and whether the site is trusted",
      "Paste your recovery phrase to confirm identity",
      "Move all savings into the same hot wallet",
      "Increase slippage to the maximum",
    ],
    correctIndex: 0,
  },
  {
    id: "c9",
    lessonId: "risk-fundamentals",
    prompt: "What does position sizing answer before a trade is opened?",
    options: [
      "How much capital should be used for the defined risk",
      "Which influencer will mention the token next",
      "Which validator produces the next block",
      "Whether the exchange will list the coin tomorrow",
    ],
    correctIndex: 0,
  },
  {
    id: "c10",
    lessonId: "risk-fundamentals",
    prompt: "Why is a trade journal useful?",
    options: [
      "It helps identify repeated mistakes and whether a strategy is working",
      "It guarantees every entry has positive expectancy",
      "It removes the need for stop-loss planning",
      "It makes liquidity checks unnecessary",
    ],
    correctIndex: 0,
  },
  {
    id: "c11",
    lessonId: "risk-fundamentals",
    prompt: "Which action is most consistent with disciplined risk management?",
    options: [
      "Skipping a setup when the invalidation point is unclear",
      "Adding size because a chat room is excited",
      "Removing the stop after price moves against you",
      "Using maximum leverage because fees are low",
    ],
    correctIndex: 0,
  },
  {
    id: "c12",
    lessonId: "risk-fundamentals",
    prompt: "What is drawdown?",
    options: [
      "A decline from an account or strategy peak",
      "A DEX router address",
      "A stablecoin redemption fee",
      "A Jito transaction tip",
    ],
    correctIndex: 0,
  },
  {
    id: "c13",
    lessonId: "meme-coins",
    prompt: "Why can a meme token with thin liquidity be hard to exit?",
    options: [
      "Selling size can move the price heavily against the trader",
      "Thin liquidity guarantees no slippage",
      "Only CEX accounts can sell tokens",
      "Stablecoins block the sell order",
    ],
    correctIndex: 0,
  },
  {
    id: "c14",
    lessonId: "meme-coins",
    prompt: "What is a common warning sign in meme coin marketing?",
    options: [
      "Guaranteed-profit claims and urgent pressure to buy immediately",
      "Clear contract links and risk disclosures",
      "A public chart with visible liquidity",
      "Open discussion of token supply",
    ],
    correctIndex: 0,
  },
  {
    id: "c15",
    lessonId: "meme-coins",
    prompt: "Why does circulating supply matter when estimating market cap?",
    options: [
      "Market cap depends on price multiplied by circulating tokens",
      "It is the same thing as daily trading volume",
      "It determines the forex pip value",
      "It removes all rug risk",
    ],
    correctIndex: 0,
  },
  {
    id: "c16",
    lessonId: "meme-coins",
    prompt: "What does it suggest if a project team can mint unlimited new tokens?",
    options: [
      "Future dilution or abuse may be possible",
      "The token is automatically a stablecoin",
      "The token cannot be sold by anyone",
      "The token has no smart contract risk",
    ],
    correctIndex: 0,
  },
  {
    id: "c17",
    lessonId: "meme-trading",
    prompt: "What is the main reason to run a small test sell on a risky new token?",
    options: [
      "To confirm selling actually works before sizing larger",
      "To increase the token's market cap permanently",
      "To remove the token tax for everyone",
      "To make the token appear on a CEX",
    ],
    correctIndex: 0,
  },
  {
    id: "c18",
    lessonId: "meme-trading",
    prompt: "How should Jito bribes or priority fees be treated in trade planning?",
    options: [
      "As part of the total execution cost",
      "As guaranteed profit after the trade",
      "As a replacement for checking liquidity",
      "As proof the token is not a scam",
    ],
    correctIndex: 0,
  },
  {
    id: "c19",
    lessonId: "meme-trading",
    prompt: "What is a likely downside of buying only because a token is trending?",
    options: [
      "The move may already be crowded and vulnerable to a sharp reversal",
      "Trending tokens cannot have liquidity",
      "Trending tokens never charge fees",
      "The wallet cannot sign the transaction",
    ],
    correctIndex: 0,
  },
  {
    id: "c20",
    lessonId: "meme-trading",
    prompt: "Why do meme traders care about transaction speed around launches?",
    options: [
      "Delayed fills can mean a very different entry price or a missed trade",
      "Fast transactions eliminate contract risk",
      "Speed determines the token's legal status",
      "Slow transactions always settle at a better price",
    ],
    correctIndex: 0,
  },
  {
    id: "c21",
    lessonId: "solana",
    prompt: "What is one practical benefit of Solana's low fees for small traders?",
    options: [
      "Small swaps and tests can be more economical",
      "Every token becomes risk-free",
      "Private keys are no longer needed",
      "Liquidation cannot occur on any exchange",
    ],
    correctIndex: 0,
  },
  {
    id: "c22",
    lessonId: "solana",
    prompt: "Which tool is commonly used to inspect Solana transactions and token accounts?",
    options: [
      "A Solana block explorer",
      "A forex economic calendar only",
      "A futures funding calculator only",
      "A prediction market resolver",
    ],
    correctIndex: 0,
  },
  {
    id: "c23",
    lessonId: "solana",
    prompt: "Why can a Solana transaction still fail even if the wallet has SOL?",
    options: [
      "Slippage, account state, congestion, or program rules can reject it",
      "SOL wallets cannot sign swaps",
      "All Solana transactions are manually approved by a bank",
      "Transactions only process once per day",
    ],
    correctIndex: 0,
  },
  {
    id: "c24",
    lessonId: "solana-memes",
    prompt: "Why can launchpad charts on Solana change quickly in the first minutes?",
    options: [
      "Buy pressure, bots, and low starting liquidity can move prices rapidly",
      "The price is fixed by the token name",
      "Only one wallet may trade at a time",
      "Stablecoins decide the opening price after a week",
    ],
    correctIndex: 0,
  },
  {
    id: "c25",
    lessonId: "solana-memes",
    prompt: "What should a trader verify before buying a Solana meme from a social link?",
    options: [
      "That the mint address matches the intended token",
      "That the token has no public holders",
      "That SOL gas is exactly zero",
      "That the creator promises a 100x return",
    ],
    correctIndex: 0,
  },
  {
    id: "c26",
    lessonId: "solana-memes",
    prompt: "What is one risk of competing with bots in Solana meme launches?",
    options: [
      "Humans may receive worse entries or exits in a fast-moving order flow",
      "Bots make every token audited",
      "Bots prevent all rugs from happening",
      "Bots convert SOL into forex lots",
    ],
    correctIndex: 0,
  },
  {
    id: "c27",
    lessonId: "bsc-memes",
    prompt: "Why is a honeypot check especially important before buying a BSC meme token?",
    options: [
      "Some malicious contracts allow buys while blocking or punishing sells",
      "It calculates the exact next Bitcoin halving date",
      "It guarantees the team cannot market the token",
      "It confirms the token is listed on every CEX",
    ],
    correctIndex: 0,
  },
  {
    id: "c28",
    lessonId: "bsc-memes",
    prompt: "What does a contract owner with broad permissions represent?",
    options: [
      "A risk that settings like taxes or trading rules may be changed",
      "A guarantee that liquidity is permanent",
      "Proof that the token is decentralized",
      "A signal that leverage is unavailable",
    ],
    correctIndex: 0,
  },
  {
    id: "c29",
    lessonId: "bsc-memes",
    prompt: "Why do traders look at liquidity depth on PancakeSwap-style pools?",
    options: [
      "It affects slippage and whether exits can absorb sell pressure",
      "It determines the pip size of EUR/USD",
      "It makes a seed phrase public",
      "It decides the stablecoin reserve audit",
    ],
    correctIndex: 0,
  },
  {
    id: "c30",
    lessonId: "crypto-futures",
    prompt: "If BTC moves 2% against a 20x leveraged position, why is the risk severe?",
    options: [
      "The loss relative to margin can be large enough to approach liquidation",
      "The position automatically becomes a spot BTC holding",
      "The exchange must refund the funding payment",
      "The trader earns 20 pips by default",
    ],
    correctIndex: 0,
  },
  {
    id: "c31",
    lessonId: "crypto-futures",
    prompt: "What does liquidation price estimate?",
    options: [
      "The price where the exchange may force-close the position due to insufficient margin",
      "The guaranteed profit target of the trade",
      "The average price of all CEX listings",
      "The stablecoin peg level",
    ],
    correctIndex: 0,
  },
  {
    id: "c32",
    lessonId: "crypto-futures",
    prompt: "Why might isolated margin be preferred by a cautious futures trader?",
    options: [
      "It limits the collateral exposed to a single position",
      "It guarantees the position cannot be liquidated",
      "It removes all trading fees",
      "It makes funding permanently positive",
    ],
    correctIndex: 0,
  },
  {
    id: "c33",
    lessonId: "crypto-futures",
    prompt: "What does notional size mean in a leveraged futures trade?",
    options: [
      "The total market exposure controlled by the position",
      "Only the fee paid to open the trade",
      "Only the stablecoin balance left unused",
      "The number of pips in a forex quote",
    ],
    correctIndex: 0,
  },
  {
    id: "c34",
    lessonId: "predictions",
    prompt: "What does buying No in a prediction market express?",
    options: [
      "A view that the stated event will not happen under the market rules",
      "A short position on Bitcoin with leverage",
      "A claim on every possible outcome",
      "A guaranteed refund if the event is delayed",
    ],
    correctIndex: 0,
  },
  {
    id: "c35",
    lessonId: "predictions",
    prompt: "Why can liquidity be a risk in prediction markets?",
    options: [
      "A trader may be unable to enter or exit size near the displayed price",
      "Resolution rules become invalid when volume is low",
      "Low liquidity guarantees better fills",
      "Markets with low liquidity cannot settle",
    ],
    correctIndex: 0,
  },
  {
    id: "c36",
    lessonId: "predictions",
    prompt: "If you think an event has a 30% chance but Yes trades at 60 cents, what is the basic concern?",
    options: [
      "The market price may be too expensive relative to your estimate",
      "The market is automatically risk-free",
      "The No side cannot be purchased",
      "The market will pay out in pips",
    ],
    correctIndex: 0,
  },
  {
    id: "c37",
    lessonId: "forex",
    prompt: "What does EUR/USD = 1.0900 mean?",
    options: [
      "One euro is priced at 1.0900 US dollars",
      "One dollar is priced at 1.0900 euros",
      "EUR is the quote currency",
      "The pair moved exactly one pip today",
    ],
    correctIndex: 0,
  },
  {
    id: "c38",
    lessonId: "orders-execution",
    prompt: "Take-profit orders are used mainly to:",
    options: [
      "Lock gains at a planned target (or scale out in parts)",
      "Hide your seed phrase",
      "Increase leverage automatically",
      "Delete open interest",
    ],
    correctIndex: 0,
  },
  {
    id: "c39",
    lessonId: "chart-basics",
    prompt: "Double top / double bottom patterns are typically:",
    options: [
      "Potential reversal ideas if the neckline breaks with follow-through",
      "Guaranteed wins with no stop needed",
      "Only valid on forex exotics",
      "The same as a market order",
    ],
    correctIndex: 0,
  },
  {
    id: "c40",
    lessonId: "orders-execution",
    prompt: "Reduce-only on futures helps you:",
    options: [
      "Avoid accidentally flipping or increasing a position when you only meant to exit",
      "Skip stop-losses forever",
      "Guarantee maker rebates on every fill",
      "Turn memes into stablecoins",
    ],
    correctIndex: 0,
  },
];
